In [1]:
import pandas as pd

In [4]:
data_temp = pd.read_csv('/lustre/geocean/WORK/users/alonsoap/personal/dodencia/AnaliticaDeDatos/datos/clases/clase_2_analisis_de_series_temporales/datos_temp.csv', skiprows=3)

In [5]:
data_temp.head()

               time  temperature_2m (°C)
0  2000-01-01T00:00                 -0.1
1  2000-01-01T01:00                 -0.2
2  2000-01-01T02:00                 -0.1
3  2000-01-01T03:00                 -0.2
4  2000-01-01T04:00                 -0.2

Cuando trabajeis con una serie temporal, lo primero es importante que la columna de fechas esté en formato datetime. Para ello, podemos usar la función pd.to_datetime() de pandas.

In [10]:
data_temp['time'] = pd.to_datetime(data_temp['time']) #### Esta función convierte la columna 'time' a un objeto de tipo datetime, lo que permite realizar operaciones de series temporales

Es conveniente además que es en el indice

In [11]:
#data_temp = data_temp.set_index('time') # Esta es una forma de hacerlo
data_temp.set_index('time', inplace=True) #### Esta función establece la columna 'time' como índice del DataFrame, lo que es útil para análisis de series temporales

In [12]:
data_temp

                     temperature_2m (°C)
time
2000-01-01 00:00:00                 -0.1
2000-01-01 01:00:00                 -0.2
2000-01-01 02:00:00                 -0.1
2000-01-01 03:00:00                 -0.2
2000-01-01 04:00:00                 -0.2
...                                  ...
2025-12-31 19:00:00                  1.4
2025-12-31 20:00:00                  1.6
2025-12-31 21:00:00                  1.7
2025-12-31 22:00:00                  1.7
2025-12-31 23:00:00                  1.8

[227928 rows x 1 columns]